/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.view;

import game.model.GameMap;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.List;
import javax.imageio.ImageIO;
import game.model.ModelObject;
import game.model.Player;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.util.Map;

/**
 *
 * @author andrej
 */
public class MainPanel extends javax.swing.JPanel {

    
    List<ModelObject> model;    //game objects
    Image backBuffer;
    BufferedImage background;
    BufferedImage texture_grass;
    BufferedImage texture_path;
    BufferedImage player;
    BufferedImage player_moving;
    BufferedImage player_right;
    BufferedImage player_moving_right;
    
    GameMap gameMap;
    
    int rows;
    int cols;
    
    private int clickedXPosition;
    private int clickedYPosition;
    
    private boolean firstClick;
    
    public int mapPos;
    public int mapXPosition;
    public int newXPosition;
    
    
    public MainPanel() {
        
        initComponents();       //pre-defined java method
        backBuffer= new BufferedImage(ModelObject.WIDTH, ModelObject.HEIGTH, BufferedImage.SCALE_DEFAULT);
        
        rows = ModelObject.AREA_WIDTH / 50;
        gameMap = new GameMap();
        mapPos = 60;
        mapXPosition = 0;
        
        try {
            background = ImageIO.read(getClass().getResource("/game/view/bground.png"));
            texture_grass = ImageIO.read(getClass().getResource("/game/view/texture_grass.png"));
            texture_path = ImageIO.read(getClass().getResource("/game/view/texture_path.png"));
            player = ImageIO.read(getClass().getResource("/game/view/player.png"));
            player_right = ImageIO.read(getClass().getResource("/game/view/player_right.png"));
            player_moving = ImageIO.read(getClass().getResource("/game/view/player_moving.png"));
            player_moving_right = ImageIO.read(getClass().getResource("/game/view/player_moving_right.png"));
            
            rows = ModelObject.AREA_WIDTH / 50; //texture_grass.getWidth();
            cols = ModelObject.AREA_HEIGHT / 50; //texture_grass.getHeight();
            
            System.out.println("ROWS: " + rows);
            System.out.println("COLS: " + cols);
            
            rows = 10;
            cols = 8;
            
        } catch (IOException ex) {
           
        }
    }
    
    @Override
    public void paintComponent(Graphics graphic) {
        super.paintComponent(graphic);
        Graphics g = backBuffer.getGraphics();
        paintBackground(g);
        if (model!=null ) {
            for(ModelObject o :model) {
                if (o instanceof Player) {
                    paintAnimatedPlayer(g, (Player) o);
                    //g.drawImage(player, o.getX(), o.getY(), player.getWidth(), player.getHeight(), null);
                } 
            }
        }

        Graphics2D graphic2d = (Graphics2D) graphic;
        graphic2d.drawImage(backBuffer, 0, 0, this.getWidth(), this.getHeight(), null);
        
    }
    
    
    
    public void updateModel(List<ModelObject> data) {
        this.model = data;
    }
    
    
    public int getClickedXPosition() {
        
        return clickedXPosition;
        
    }
    
    public int getClickedYPosition() {
        
        return clickedYPosition;
    }
    
    
    public boolean isClicked() {
        
        return firstClick;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        
        if(firstClick == false)
        {
            firstClick = true;
        }
        
        clickedXPosition = evt.getX();
        clickedYPosition = evt.getY();
    }//GEN-LAST:event_formMouseReleased
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
